# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cutter's Crossing
email: "web.admin@cutterscrossing.com"
description: >- # this means to ignore newlines until "baseurl:"
  We talk about web development, often covering the three core pillars: HTML, CSS, and Javascript. There is a lot of legacy content here, discussing everything from ColdFusion to ExtJs, as well as more current stuff like modern EcmaScript, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cutterscrossing.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
repository: cutterbl/cutterbl.github.io
twitter_username: cutterbl
github_username:  cutterbl

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - github-pages

remote_theme: daviddarnes/alembic

exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache

paginate: 4 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: cutterbl # jekyll-seo-tag > Owners twitter username
author: CutterBlades # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Cutter Blades # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/cutterbl
    - https://www.facebook.com/CutterBlades
    - https://www.linkedin.com/in/stephen-blades-05223919
    - https://github.com/cutterbl
    - https://instagram.com/bladesphoto

timezone: America/Chicago

lang: en-us

navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: About
  url: /about/
- title: Search
  url: /search/

navigation_footer:
- title: See My Photography
  url: https://blades.photo

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/cutterbl
  LinkedIn: https://www.linkedin.com/in/stephen-blades-05223919
  GitHub: https://github.com/cutterbl
  link: https://blades.photo
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true